baseURL = "https://nmudos.com/"
languageCode = "en-us"
title = "nMudOS"
themesDir = "themes"
theme = "bigspring"
publishDir = "docs"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

paginate = "3"
summaryLength = "15"
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


############################## navigation ###############################


[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 1

[[menu.main]]
    name = "Documents"
    url = "docs"
    weight = 3

[[menu.main]]
    name = "References"
    url = "/references/"
    weight = 4

[[menu.main]]
    name = "Language"
    url = "/language/"
    weight = 5

[[menu.main]]
    name = "Client"
    url = "/client/"
    weight = 6

[[menu.main]]
    parent = "Language"
    name = "LPC Language"
    url = "/language/lpc/"
    weight = 1

[[menu.main]]
    parent = "Language"
    name = "Lua Language"
    url = "/language/lua/"
    weight = 2

[[menu.main]]
    parent = "Language"
    name = "JavaScript Language"
    url = "/language/js/"
    weight = 3

[[menu.main]]
    parent = "References"
    name = "efun"
    url = "/ref/efun/"
    weight = 1

[[menu.main]]
    parent = "References"
    name = "apply"
    url = "/ref/apply/"
    weight = 2

[[menu.main]]
    parent = "References"
    name = "stdlib"
    url = "/ref/stdlib/"
    weight = 3

# footer menu left
[[menu.footer_left]]
name = "About"
URL = "/about"

[[menu.footer_left]]
name = "Join us"
URL = "/joinus"

[[menu.footer_left]]
name = "Donate"
URL = "donate"

# footer menu middle
[[menu.footer_middle]]
name = "nt7-game"
URL = "https://github.com/nmudos/nt7"

[[menu.footer_middle]]
name = "Client"
URL = "https://github.com/nmudos/nmudc"

[[menu.footer_middle]]
name = "nMudOS"
URL = "https://github.com/nmudos/nmudos"

# footer menu right
[[menu.footer_right]]
name = "Issues"
URL = "https://github.com/nmudos/nmudos/issues"

[[menu.footer_right]]
name = "Discussions"
URL = "https://github.com/nmudos/nmudos/discussions"

[[menu.footer_right]]
name = "License"
URL = "https://github.com/nmudos/nmudos/blob/main/LICENSE"


#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "200px"

########### footer content ##########
footer_menu_left = "Team"
footer_menu_middle = "Github"
footer_menu_right = "Support"
footer_content = "nMudOS is a modern mud game drive."
# copyright
copyright = "The nMudOS logos are copyright © Xinlei Zhang 2020–2021. Develop By [mebius](mebius@ashan.org) . The Website Design By [Themefisher](https://themefisher.com/)"

# Navigation buttons
[params.navigation_button]
enable = true
label = "Get Started"
link = "/docs/"


  
############################# social site ########################
[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/nmudos"

[[params.social]]
title = "email"
icon = "ti-email" # themify icon : https://themify.me/themify-icons
link = "mebius@ashan.org"